language: python

python:

 - 3.6.1

service:
  - postgresql

cache: pip

before_install:
  - export DATABASE_URL_TEST="postgresql://postgres@localhost/test_api"
  - export APP_SETTINGS="app.config.TestingConfig"


install:
  - pip install coveralls
  - pip install coverage
  - pip install flask
  - pip install -r requirements.txt

env:
  CODECLIMATE_REPO_TOKEN: 51e5a99bea397fbd30ad2ad81a09d8e69499482f2caed901606f1d255d4cdf06


before_script:
  - psql -c 'create database test_api;' -U postgres
  - python manage.py db upgrade

script:
  -  nosetests --with-coverage

after_script:
  - coveralls
  