language: python

python:

 - 3.6.1

cache: pip


install:
  - pip install coveralls
  - pip install coverage
  - pip install flask

env:
  CODECLIMATE_REPO_TOKEN: 51e5a99bea397fbd30ad2ad81a09d8e69499482f2caed901606f1d255d4cdf06


script:
  - nosetests --with-coverage --cover-package=app

after_success:
  - coveralls