"""empty message

Revision ID: 0147b5701b67
Revises: 9358a08f9ac7
Create Date: 2017-08-23 15:06:31.769737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0147b5701b67'
down_revision = '9358a08f9ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'shoppinglists', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shoppinglists', type_='unique')
    # ### end Alembic commands ###
