"""empty message

Revision ID: 49bcb6ad2453
Revises: 
Create Date: 2017-08-24 03:48:09.015447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49bcb6ad2453'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('price', sa.String(length=250), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['shoppinglists.list_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.add_column('shoppinglists', sa.Column('list_id', sa.Integer(), nullable=False))
    op.drop_column('shoppinglists', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoppinglists', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('shoppinglists', 'list_id')
    op.drop_table('items')
    # ### end Alembic commands ###
