"""empty message

Revision ID: 69b21ca7c08c
Revises: 7db69155a4bc
Create Date: 2017-09-01 21:54:52.587981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69b21ca7c08c'
down_revision = '7db69155a4bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shoppinglists_search_vector', table_name='shoppinglists')
    op.drop_column('shoppinglists', 'search_vector')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoppinglists', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index('ix_shoppinglists_search_vector', 'shoppinglists', ['search_vector'], unique=False)
    # ### end Alembic commands ###
