"""empty message

Revision ID: 7db69155a4bc
Revises: 
Create Date: 2017-09-01 17:49:19.064608

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '7db69155a4bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoppinglists',
                  sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    op.create_index('ix_shoppinglists_search_vector', 'shoppinglists', ['search_vector'], unique=False,
                    postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shoppinglists_search_vector', table_name='shoppinglists')
    op.drop_column('shoppinglists', 'search_vector')
    # ### end Alembic commands ###
