"""empty message

Revision ID: 8fcf118fa6aa
Revises: 0147b5701b67
Create Date: 2017-08-23 17:04:32.087780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fcf118fa6aa'
down_revision = '0147b5701b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('price', sa.String(length=250), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('shoppinglists_name_key', 'shoppinglists', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('shoppinglists_name_key', 'shoppinglists', ['name'])
    op.drop_table('items')
    # ### end Alembic commands ###
